source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'libmuse_Example', :exclusive => true do
  pod "libmuse", :path => "../"
end

target 'libmuse_Tests', :exclusive => true do
  pod "libmuse", :path => "../"

  
end
